### ISSUE TITLE
How do I get the editor back after clicking "remove editor" in the heroku demo? 

### ISSUE THREAD

**Issue by retorquere** [guillaumejacquart/stupid-cms-db#4]
After clicking "remove editor" in the heroku demo the editor dutifully disappears, but I see no way to get it back. I've re-logged-in, removed the cookies relevant to the site, hard-reloaded, but the editor doesn't come back.

**Comment by guillaumejacquart** [comment]
You can re-add the editor by right clicking on the html element you want to make editable. a "pencil" icon button should appear on the right side of the element. When you click on it, you will be able to edit the content again.
I'll add an issue regarding the lack of user documentation.

**Comment by retorquere** [comment]
When I click the pencil, I get

> The selector is incorrect: 0 matches. You must set the editable content manually

**Comment by guillaumejacquart** [comment]
This means the DOM was change with JS compared to the original HTML on the file. The CMS cannot then find the element to set as editable on the file. It can happen if the HTML template is too much dynamic. What element did you try to make editable ?

**Comment by retorquere** [comment]
The "DIMENSION" text. I clicked it, removed the editor, right-clicked and clicked the pencil, and then I get the error.

**Comment by guillaumejacquart** [comment]
All right i experienced the issue as well. I'll investigate. If we want to contribute please do I'll merge your pull request. In the meantime it seems like it's working when you reload the page after removing the editor.

**Comment by guillaumejacquart** [comment]
Could you test it again ? I commited changes to the editor selection that should fix the issue.

**Comment by retorquere** [comment]
Yep, seems to work fine now.
